import Head from "next/head";
import Layout from "../components/Layout";
import ProductController from "../components/ProductController";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Mriya Store</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <ProductController />
      </Layout>
    </div>
  );
}
